### ISSUE TITLE
>:^(

### ISSUE THREAD

**Issue by cheuble** [TheKingy34/11.0-Downgrader#2]
I'm not happy because your tool bullied my 3DS, now it is giving me a rainbow screen of death, please fix

**Comment by Kingy34** [comment]
sir your 3ds has been hacked please call our technicians and give us your credit card number and mother's maiden name and well get this started.

Also, are you using Windows 10 to download this

**Comment by cheuble** [comment]
> Are you using Windows 10 to download this

Yes, and I'm proud of this. If you're downgrader doesn't work on this, I'm going to sue you for OS bullying!

**Comment by Kingy34** [comment]
> I'm going to sue you for OS [bullying!] 

too fucking bad, peasant. You can only use this if you have no spyware.
